### ISSUE TITLE
Expose a healthcheck endpoint

### ISSUE THREAD

**Issue by tomelliff** [psyinfra/prometheus-raritan-pdu-exporter#5]
Thanks for this, we had a bunch of pain trying to get SNMP exporting work with the [SNMP exporter](https://github.com/prometheus/snmp_exporter) for our Raritan PDUs while this just worked out of the box without my brain having to think about OIDs and MIB files :joy_cat: 

We are deploying this into a Kubernetes cluster but liveness probes cause a scrape of the configured Raritan PDUs because the `prometheus_client.start_http_server` returns the metrics for any requests. This is slower and more expensive than we'd like for a liveness probe and it initially caused the pod to be restarted aggressively. While we've backed off the probes and allowed a longer timeout on them it would be nice to instead have a basic `/healthcheck` or `/healthz` etc endpoint that just shows that the HTTP server is up and running.

[This example](https://prometheus.github.io/client_python/exporting/http/flask/) shows how you can expose a `/metrics` endpoint as part of a larger Flask app and I was thinking it might be nice to do that but just provide a single other healthcheck endpoint in Flask and then push `/metrics` to the `prometheus_client.make_wsgi_app` method.

**Comment by nhjjr** [comment]
Hey tomelliff, glad to hear we rescued someone from the clutches of SNMP ;) Adding big dependencies like Flask and werkzeug to this exporter is, in my opinion, undesirable, as it creates more overhead for an otherwise non-standard functionality for Prometheus exporters. You are, of course, free to create a fork with this functionality.

Furthermore, with Raritan picking up support for their own native exporter (which hopefully becomes a bit more stable in the future) I'd rather leave this exporter as-is (barring bug-fixes) rather than develop it further.

**Comment by aqw** [comment]
I think a simpler alternative to introducing flask, et al is to add a separate endpoint at `/healthcheck`, and simply expose the default prometheus stats there without invoking the raritan checks.

If that would fulfill your requirements @tomelliff, then I would be very open to accepting a PR with this approach. :-)

**Comment by tomelliff** [comment]
> Furthermore, with Raritan picking up support for their own native exporter (which hopefully becomes a bit more stable in the future) I'd rather leave this exporter as-is (barring bug-fixes) rather than develop it further.

Do you have a link to this project? I can't seem to find any mention of it anywhere.

And yeah, appreciate that this isn't an issue for people running the exporter outside of places where there's healthchecks so you might not want a heavy dependency. Unfortunately I don't see a good way to handle routing inside the Prometheus client server and if you don't want a dependency introducing to handle different URL routing I'm not sure where we'd make the change?

The hacky way that I could see it is to write our own `make_wsgi_app` that returns a `prometheus_app` that checks the path there. I don't think the `environ` from the `wsgiref` request is exposed elsewhere in a way that it's possible to hook into? That makes me a little uncomfortable because it's basically patching upstream and it seems like a better fix would be to have that in the Prometheus client library. But I don't see any upstream issues for that which suggests to me that I'm missing something because I don't think it's uncommon to run exporters in Kubernetes or something else that will be health checking the process.

**Comment by aqw** [comment]
> Do you have a link to this project? I can't seem to find any mention of it anywhere.

The exporter is included with their firmware starting in 4.0.10/4.0.20.

https://cdn1.raritan.com/download/pdu-g2/4.0.10/Xerus_ReleaseNotes_4.0.10.pdf

Ironically, it isn't as performant as our (external) exporter. We reported the issues upstream. They acknowledge it, but say it's low priority and will require changing the way they scrape the values internally.

**Comment by nhjjr** [comment]
The native Raritan PDU exporter is described only in the [Raritan User Guide](https://cdn1.raritan.com/download/pdu-g2/4.0.20/PDU_G2_UG_A2_4.0.20.pdf) (p.352; although you should check if the PDU and firmware version you're using has this feature).

To get multiple endpoints, it is _likely_ possible to write your own `MetricsHandler` for the `prometheus_client` Python library that can redirect based on the requested endpoint as @aqw suggests. Something akin to [this stackoverflow post](https://stackoverflow.com/questions/69175661/configure-exporter-python-prometheus-client-with-multiple-targets) could likely work.

**Comment by tomelliff** [comment]
Ah, okay, looks like most of our PDUs are on an older firmware version but we could consider bumping them in future.

Talking of which, would you be okay with adding the PDU metadata (what's returned from calling `getMetaData` on `/model/pdu/0`) as a metric here? We have a similar thing with [the Dell HW exporter](https://github.com/galexrt/dellhw_exporter) where seeing eg the firmware version in a table can be helpful to track older boxes. I'm happy to raise a separate issue for that though.

Also, thanks for that link @nhjjr, I think I have something working in #6 which works okay for me locally from some quick testing.
